[package]
name = "persian-tools"
version = "0.1.0"
authors = ["rustland-fa developers"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/rustland-fa/persian-tools-rs"
description = """
A set of tools and helpers related to Persian language or in general, Iran!
"""
keywords = ["persian", "tool", "format", "tools", "iran"]
categories = ["algorithms", "date-and-time", "encoding", "internationalization", "localization"]
include = ["src/", "*.md"]

[dependencies]
lazy_static = "1.4.0"
regex = "1.4.3"
phf = { version = "0.8", features = ["macros"] }
#ptime = "0.1.1"
#time = "0.2.25"

[features]
default = ["card_number"]
card_number = []
