[package]
name = "persian-tools-rs"
version = "0.1.0"
authors = ["robatipoor <mahdi.robatipoor@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
regex = "1.4.3"
phf = { version = "0.8", features = ["macros"] }
ptime = "0.1.1"
time = "0.2.25"
